(function(){
  const VERIFIED_STABLES=new Map([
    ['0x833589fcd6edb6e08f4c7c32d4f71b54bda02913',{symbol:'USDC',name:'USD Coin',source:'Circle/Base'}],
    ['0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca',{symbol:'USDbC',name:'USD Base Coin',source:'Circle bridge reference'}],
    ['0x60a3e35cc302bfa44cb288bc5a4f316fdb1adb42',{symbol:'EURC',name:'EURC',source:'Circle'}],
    ['0x50c5725949a6f0c72e6c4a641f24049a917db0cb',{symbol:'DAI',name:'Dai Stablecoin',source:'Maker/Base explorer'}]
  ]);
  const DAY=86400;
  function units(raw,decimals=18){const s=String(raw||'0');const d=Number(decimals||0);if(!/^\d+$/.test(s))return Number(raw||0);if(d===0)return Number(s);const p=s.padStart(d+1,'0');return Number(`${p.slice(0,-d)}.${p.slice(-d).replace(/0+$/,'').slice(0,12)||0}`)}
  function transferTs(t){const p=Date.parse(t?.timestamp||'');return Number.isFinite(p)?Math.floor(p/1000):0}
  function tokenAddress(t){return String(t?.token?.address_hash||t?.token?.address||'').toLowerCase()}
  function stableMeta(t){return VERIFIED_STABLES.get(tokenAddress(t))||null}
  function stableTransfer(t){return Boolean(stableMeta(t))&&String(t?.token?.type||'ERC-20')==='ERC-20'}
  function amount(t){return units(t?.total?.value||0,t?.token?.decimals??t?.total?.decimals??18)}
  function summarize(transfers,address,start,end){
    const a=String(address||'').toLowerCase();let inbound=0,outbound=0,inUsd=0,outUsd=0;const counterparties=new Map();const symbols=new Map();let count=0;
    for(const t of transfers||[]){const time=transferTs(t);if(time<start||time>=end||!stableTransfer(t))continue;const from=String(t?.from?.hash||'').toLowerCase(),to=String(t?.to?.hash||'').toLowerCase();if(from!==a&&to!==a)continue;count++;const q=amount(t),rate=Number(t?.token?.exchange_rate||0),usd=q*rate,meta=stableMeta(t),sym=meta?.symbol||String(t?.token?.symbol||'');const incoming=to===a;if(incoming){inbound++;inUsd+=usd}else{outbound++;outUsd+=usd}symbols.set(sym,(symbols.get(sym)||0)+usd);const cp=incoming?from:to;if(cp)counterparties.set(cp,(counterparties.get(cp)||0)+1)}
    return{count,inbound,outbound,inUsd,outUsd,netUsd:inUsd-outUsd,counterparties:[...counterparties.entries()].sort((a,b)=>b[1]-a[1]),symbols:[...symbols.entries()].sort((a,b)=>b[1]-a[1])};
  }
  function pageOldestTimestamp(items){let oldest=Infinity;for(const item of items||[]){const ts=transferTs(item);if(ts&&ts<oldest)oldest=ts}return Number.isFinite(oldest)?oldest:0}
  async function fetchTransfers(address,options={}){
    const maxPages=Math.max(1,Math.min(20,Number(options.maxPages||10)));
    const sinceTs=Number(options.sinceTs||0);
    let url=`https://base.blockscout.com/api/v2/addresses/${encodeURIComponent(address)}/token-transfers?type=ERC-20`,items=[],pages=0,complete=false,oldestTimestamp=0;
    for(let page=0;page<maxPages&&url;page++){
      const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`Token transfer API ${r.status}`);
      const j=await r.json(),batch=j.items||[];pages++;items.push(...batch);
      const batchOldest=pageOldestTimestamp(batch);if(batchOldest)oldestTimestamp=oldestTimestamp?Math.min(oldestTimestamp,batchOldest):batchOldest;
      if(sinceTs&&batchOldest&&batchOldest<=sinceTs){complete=true;break}
      const p=j.next_page_params;if(!p){complete=true;break}
      const q=new URLSearchParams({type:'ERC-20'});Object.entries(p).forEach(([k,v])=>{if(v!=null)q.set(k,String(v))});url=`https://base.blockscout.com/api/v2/addresses/${encodeURIComponent(address)}/token-transfers?${q}`;
    }
    items.coverage={pages,maxPages,sinceTs,oldestTimestamp,complete};return items;
  }
  function ensureUI(){if(document.getElementById('stablecoinFlow'))return;const anchor=document.getElementById('baseAppGraph')||document.getElementById('behaviorDelta')||document.querySelector('.fingerprint-card');if(!anchor)return;const el=document.createElement('article');el.id='stablecoinFlow';el.className='card section-card stable-flow-card';el.innerHTML=`<div class="card-head"><div><div class="eyebrow">STABLECOIN & PAYMENT BEHAVIOR</div><h3>How verified stable value moves through this wallet</h3></div><span class="badge">Verified Base contracts</span></div><p class="section-intro">A descriptive view of indexed transfers for explicitly allowlisted Base stablecoin contracts. Token symbols alone are never trusted. This is not a credit, solvency, income, or risk assessment.</p><div id="stableFlowStatus" class="stable-flow-status">Loading token-transfer history…</div><div class="stable-flow-grid"><div><span>30d inbound</span><strong id="stableIn">—</strong><small id="stableInCount">—</small></div><div><span>30d outbound</span><strong id="stableOut">—</strong><small id="stableOutCount">—</small></div><div><span>30d net flow</span><strong id="stableNet">—</strong><small>priced transfers only</small></div><div><span>Verified stable transfers</span><strong id="stableCount">—</strong><small id="stableCountTrend">—</small></div></div><div class="stable-flow-bottom"><div><div class="eyebrow">TOP COUNTERPARTIES</div><div id="stableCounterparties" class="stable-list"></div></div><div><div class="eyebrow">VERIFIED STABLECOIN MIX BY FLOW</div><div id="stableSymbols" class="stable-list"></div></div></div>`;anchor.insertAdjacentElement('afterend',el);const style=document.createElement('style');style.textContent=`.stable-flow-card{background:radial-gradient(circle at 15% 0,rgba(74,222,128,.08),transparent 35%),linear-gradient(180deg,rgba(17,26,42,.98),rgba(9,14,24,.98))}.stable-flow-status{margin-top:14px;color:#718096;font-size:12px}.stable-flow-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.stable-flow-grid>div{background:#080d16;border:1px solid #19243a;border-radius:14px;padding:14px}.stable-flow-grid span{display:block;color:#9facbf;font-size:12px}.stable-flow-grid strong{display:block;font-size:22px;margin:7px 0}.stable-flow-grid small{color:#718096;font-size:11px}.stable-flow-bottom{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:20px;padding-top:18px;border-top:1px solid #18243a}.stable-list{display:grid;gap:7px}.stable-row{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid #182235;font-size:12px;color:#aebbd0}.stable-row a{color:#9bc0ff;text-decoration:none}.stable-positive{color:#4ade80!important}.stable-negative{color:#fb7185!important}@media(max-width:850px){.stable-flow-grid{grid-template-columns:repeat(2,1fr)}.stable-flow-bottom{grid-template-columns:1fr}}`;document.head.appendChild(style)}
  function money(v){const n=Number(v||0);if(!Number.isFinite(n))return '$0.00';return n.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:n>=100?0:2})}
  function short(a){return a?`${a.slice(0,8)}…${a.slice(-6)}`:'—'}
  function renderRows(id,rows,type){const root=document.getElementById(id);if(!root)return;root.innerHTML='';if(!rows.length){root.innerHTML='<div class="delta-empty">None detected in fetched history.</div>';return}rows.slice(0,7).forEach(([key,val])=>{const d=document.createElement('div');d.className='stable-row';d.innerHTML=type==='address'?`<a href="https://base.blockscout.com/address/${encodeURIComponent(key)}" target="_blank" rel="noreferrer">${short(key)} ↗</a><strong>${val} transfers</strong>`:`<span>${key}</span><strong>${money(val)}</strong>`;root.appendChild(d)})}
  async function render(){ensureUI();if(typeof state==='undefined'||!state.address)return;const status=document.getElementById('stableFlowStatus');try{status.textContent='Reading indexed Base token transfers…';const now=Math.floor(Date.now()/1000),sinceTs=now-90*DAY,transfers=await fetchTransfers(state.address,{sinceTs,maxPages:10}),cur=summarize(transfers,state.address,now-30*DAY,now+1),prev=summarize(transfers,state.address,now-60*DAY,now-30*DAY);document.getElementById('stableIn').textContent=money(cur.inUsd);document.getElementById('stableOut').textContent=money(cur.outUsd);const net=document.getElementById('stableNet');net.textContent=`${cur.netUsd>=0?'+':''}${money(cur.netUsd)}`;net.className=cur.netUsd>=0?'stable-positive':'stable-negative';document.getElementById('stableCount').textContent=cur.count.toLocaleString();document.getElementById('stableInCount').textContent=`${cur.inbound} inbound transfers`;document.getElementById('stableOutCount').textContent=`${cur.outbound} outbound transfers`;const trend=prev.count?((cur.count-prev.count)/prev.count)*100:(cur.count?'new':0);document.getElementById('stableCountTrend').textContent=trend==='new'?'new vs previous 30d':`${trend>=0?'+':''}${Math.round(trend)}% vs previous 30d`;renderRows('stableCounterparties',cur.counterparties,'address');renderRows('stableSymbols',cur.symbols,'symbol');const c=transfers.coverage||{};const coverageText=c.complete?'90-day history target reached or explorer history exhausted':`history capped after ${c.pages||0} pages before the 90-day target`;status.textContent=`Fetched ${transfers.length} recent ERC-20 records across ${c.pages||0} page${c.pages===1?'':'s'}; ${coverageText}. Counted only ${VERIFIED_STABLES.size} explicitly allowlisted Base stablecoin contracts.`;globalThis.BaseStablecoinFlow.last={transfers,current:cur,previous:prev,coverage:c,verifiedContracts:[...VERIFIED_STABLES.entries()].map(([address,meta])=>({address,...meta}))};}catch(e){status.textContent=`Stablecoin transfer view unavailable: ${e.message}`}}
  function init(){ensureUI();const d=document.getElementById('dashboard');if(!d)return;new MutationObserver(()=>{if(!d.classList.contains('hidden'))render()}).observe(d,{attributes:true,attributeFilter:['class']});const s=document.getElementById('status');if(s)new MutationObserver(()=>{if(!d.classList.contains('hidden'))render()}).observe(s,{childList:true,subtree:true});if(!d.classList.contains('hidden'))render()}
  globalThis.BaseStablecoinFlow={VERIFIED_STABLES,stableMeta,stableTransfer,summarize,pageOldestTimestamp,fetchTransfers,last:null};if(typeof document!=='undefined')init();
})();
